spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/sisg6_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nycri2134
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.thymeleaf.cache=false
spring.web.resources.cache.period=0